// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC506V8n8MtMxGXyY5mrR2y_kD4BEFytBA',
    appId: '1:1008278824750:web:9a22d1b22f5087a8b5bcbf',
    messagingSenderId: '1008278824750',
    projectId: 'nutrimama-5d667',
    authDomain: 'nutrimama-5d667.firebaseapp.com',
    storageBucket: 'nutrimama-5d667.firebasestorage.app',
    measurementId: 'G-1STHLWS63V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnHuqJ1lOxcOI2OSJ9J710qUfFb7MIX6o',
    appId: '1:1008278824750:android:4fb74f044669ef0db5bcbf',
    messagingSenderId: '1008278824750',
    projectId: 'nutrimama-5d667',
    storageBucket: 'nutrimama-5d667.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMMvn2QdqvH0Ev_wOMV3r_L_jXZvchohw',
    appId: '1:1008278824750:ios:868c1bd193b28743b5bcbf',
    messagingSenderId: '1008278824750',
    projectId: 'nutrimama-5d667',
    storageBucket: 'nutrimama-5d667.firebasestorage.app',
    iosClientId: '1008278824750-fjrb87mf85s7lo6hgrulfs72ov3i8srk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNutrimama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMMvn2QdqvH0Ev_wOMV3r_L_jXZvchohw',
    appId: '1:1008278824750:ios:868c1bd193b28743b5bcbf',
    messagingSenderId: '1008278824750',
    projectId: 'nutrimama-5d667',
    storageBucket: 'nutrimama-5d667.firebasestorage.app',
    iosClientId: '1008278824750-fjrb87mf85s7lo6hgrulfs72ov3i8srk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNutrimama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKraYtRYaf-Mo6Ty5JQY6RME5zEgpz1HI',
    appId: '1:1008278824750:web:1be50289dc4d969bb5bcbf',
    messagingSenderId: '1008278824750',
    projectId: 'nutrimama-5d667',
    authDomain: 'nutrimama-5d667.firebaseapp.com',
    storageBucket: 'nutrimama-5d667.firebasestorage.app',
    measurementId: 'G-RNG96LY4YD',
  );

}